jecportal/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('portal.urls'))
]

portal/urls.py
from django.urls import path
from . import views

app_name = 'portal'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('index/',views.index, name='index'),
    path('portal/create/', views.AttendCreateView.as_view(), name='attend_create'),
    path('portal/create/complete/', views.AttendCreateCompleteView.as_view(), name='attend_create_complete'),
    path('portal/list/', views.AttendListView.as_view(), name='attend_list'),
    path('portal/list/<uuid:pk>/', views.AttendDetailView.as_view(), name='attend_detail'),
]

portal/models.py
from django.db import models
from django.utils import timezone
import uuid
# Create your models here.

class Attend(models.Model):
    id =models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    number=models.CharField(verbose_name='学籍番号', max_length=40)
    nationality=models.CharField(verbose_name='国籍', max_length=40)
    name=models.CharField(verbose_name='名前', max_length=40)
    kana=models.CharField(verbose_name='フリガナ', max_length=40)
    gender=models.CharField(verbose_name='男女', max_length=40)
    email=models.CharField(verbose_name='メールアドレス', max_length=40)
    abbre=models.CharField(verbose_name='ユーザーネーム', max_length=40)

portal/forms.py
from django import forms
from .models import Attend
 
 
class AttendForm(forms.ModelForm):
    class Meta:
        model = Attend
        fields = (  'number',
                    'nationality',
                    'name',
                    'kana',
                    'gender',
                    'email',
                    'abbre')

portal/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView,CreateView,ListView,DetailView,UpdateView,DeleteView
from .forms import AttendForm
from .models import Attend
# Create your views here.

class IndexView(TemplateView):
    template_name = 'index.html'

    

class AttendCreateView(CreateView):
    template_name = 'attend_create.html'
    form_class = AttendForm
    success_url = reverse_lazy('portal:attend_create_complete')

class AttendCreateCompleteView(TemplateView):
    template_name = 'attend_create_complete.html'

class AttendListView(ListView):
    template_name = 'attend_list.html'
    model = Attend

class AttendDetailView(DetailView):
    template_name = 'attend_detail.html'
    model = Attend

def index(request):
    if request.method == 'POST':
            name=request.POST['name']
            password = request.POST['pass']
            print(password)
            context={
                "name":name,
                "age":password
            }
            return render(request, 'index.html',context)
    else:
        context={
            "name":"",
            "age":""
        }
        return render(request, 'index.html',context)

templates/attend_create.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="form-group">
        <label>{{ form.number.label }}</label>
            {{ form.number | add_class:'form-control col-3' }}
    </div>
    <div class="form-group">
        <label>{{ form.nationality.label }}</label>
            {{ form.nationality | add_class:'form-control col-3' }}
    </div>
    <div class="form-group">
        <label>{{ form.name.label }}</label>
            {{ form.name | add_class:'form-control col-3' }}
    </div>
    <div class="form-group">
        <label>{{ form.kana.label }}</label>
            {{ form.kana | add_class:'form-control col-3' }}
    </div>
    <div class="form-group">
        <label>{{ form.gender.label }}</label>
            {{ form.gender | add_class:'form-control col-3' }}
    </div>
    <label>{{ form.email.label }}</label>
            {{ form.email | add_class:'form-control col-3' }}
            <label>{{ form.abbre.label }}</label>
            {{ form.abbre | add_class:'form-control col-3' }}</br>
    
    <button type="submit">登録</button>
</form>
<a href="{% url 'portal:index' %}">戻る</a>
{% endblock %}

templates/attend_create_complete.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>JECAI</title>
</head>
<body>
<p>学生の登録が完了しました！</p>
<a href="{% url 'portal:index' %}">トップへ戻る</a>
</body>
</html>

templates/attend_detail.html
{% extends 'base.html' %}
{% block content %}
    <p>{{ attend.number | add_class:'form-control' }}</p>
    <p>{{ attend.name }}</p>
    <p>{{ attend.email }}</p>
    <a href="{% url 'portal:attend_list' %}">戻る</a>
{% endblock %}

templates/attend_list.html
{% extends 'base.html' %}
{% block content %}
{% for attend in attend_list %}
<li>
    {{ attend.number }}
    <a href="{% url 'portal:attend_detail' attend.pk %}">{{ attend.name }}</a>
</li>
<a href="{% url 'portal:index' %}">戻る</a>
{% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="jp">
{% bootstrap_css %}
<head>
    <meta charset="UTF-8">
    <title>JEC_AIportal</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
<h1>日本工科大学校AI工学部最終課題</h1>
<h2>学生向けポータルサイト</h2>
<p>ようこそ　{{ name }} {{ pass }}</p>
<form action="{% url 'portal:index' %}" method="post">
    {% csrf_token %}
    <div>
        <label for="name">学籍番号</label>
        <input type="text" id="name" name="name">
    </div>
    <div>
        <label for="pass">パスワード</label>
        <input type="password" id="pass" name="pass">
    </div>
    <input type="submit" value="ログイン">
</form>

<a href="{% url 'portal:attend_create' %}">学生登録</a>
<a href="{% url 'portal:attend_list' %}">学生一覧</a>
{% endblock %}